// <auto-generated />
using System;
using DTO;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DTO.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.12");

            modelBuilder.Entity("Entitites.Kitap", b =>
                {
                    b.Property<string>("BarkodNo")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("BasimTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("KitapAd")
                        .HasColumnType("TEXT");

                    b.Property<int>("KitapTuru")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KitapYazar")
                        .HasColumnType("TEXT");

                    b.Property<int>("SayfaSayısı")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Stok")
                        .HasColumnType("INTEGER");

                    b.HasKey("BarkodNo");

                    b.ToTable("Kitaps");
                });

            modelBuilder.Entity("Entitites.Models.KutuphaneIslem", b =>
                {
                    b.Property<int>("IslemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AlimTarihi")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("IadeTarihi")
                        .HasColumnType("TEXT");

                    b.Property<double>("IslemUcret")
                        .HasColumnType("REAL");

                    b.Property<string>("KitapBarkodNo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OgrenciID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SonTeslimTarihi")
                        .HasColumnType("TEXT");

                    b.HasKey("IslemId");

                    b.HasIndex("KitapBarkodNo");

                    b.HasIndex("OgrenciID");

                    b.ToTable("KutuphaneIslems");
                });

            modelBuilder.Entity("Entitites.Models.Ogrenci", b =>
                {
                    b.Property<string>("OgrenciTC")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DogumTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("IsimSoyisim")
                        .HasColumnType("TEXT");

                    b.Property<string>("TelefonNo")
                        .HasColumnType("TEXT");

                    b.HasKey("OgrenciTC");

                    b.ToTable("Ogrencis");
                });

            modelBuilder.Entity("Entitites.Models.KutuphaneIslem", b =>
                {
                    b.HasOne("Entitites.Kitap", "Kitap")
                        .WithMany("kutuphaneIslems")
                        .HasForeignKey("KitapBarkodNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entitites.Models.Ogrenci", "Ogrenci")
                        .WithMany("kutuphaneIslems")
                        .HasForeignKey("OgrenciID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kitap");

                    b.Navigation("Ogrenci");
                });

            modelBuilder.Entity("Entitites.Kitap", b =>
                {
                    b.Navigation("kutuphaneIslems");
                });

            modelBuilder.Entity("Entitites.Models.Ogrenci", b =>
                {
                    b.Navigation("kutuphaneIslems");
                });
#pragma warning restore 612, 618
        }
    }
}
